### ISSUE TITLE
Only check staged files in precommit hook

### ISSUE THREAD

**Issue by mgred** [MathisBullinger/froebel#8]
When commiting changes to the code all typescript files are checked to be in the right format. I think its enogh to check only files beloning to the current change. What do you think @MathisBullinger ?

**Comment by MathisBullinger** [comment]
I don't think that's necessary right now. Running `deno fmt --check *.ts` currently only takes about 28 milliseconds on my machine, so it's not a performance consideration.
Generally, you should not have any unrelated changes in your working tree when committing. If you do, you can always temporarily stash them or just format them by running `deno fmt *.ts`.
